# Generated by Django 2.2.6 on 2019-11-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
