# Generated by Django 2.2.6 on 2019-11-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
